# Generated by Django 5.2.6 on 2025-10-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_app', '0004_servicelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelist',
            name='description',
        ),
    ]
