# Generated by Django 5.2.6 on 2025-10-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_app', '0005_remove_servicelist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='servicesdetail/')),
            ],
        ),
    ]
