# Generated by Django 5.2.6 on 2025-10-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_app', '0006_servicedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='residentialservices/')),
            ],
        ),
    ]
